### ISSUE TITLE
hdf_task file too large for memory

### ISSUE THREAD

**Issue by aaronjfisher** [qcri/sleep_awake_benchmark#1]
Hi!

Thanks so much for making this available! I'm interested in rerunning this code to get a benchmark for performance and compute time.

I hit a wall in the pipeline though in sleep_formulas.py, where I need to load the hdf_task file into memory. For me, this file is about 6Gb and my computer crashes when I try to load it. 

Is it supposed to be that big? In contrast, the dftest_task1.csv file is only 20Mb or so. Would it be possible to make a lighter version of that file? Do you have any advice on getting through this obstacle? I'm not sure how tractable it will be for me to run this pipeline versus rewriting my own. 

Thanks so much!
-Aaron

**Comment by joaopalotti** [comment]
Hi Aaron,

Thanks for your interest in our work! 

You are right. When I wrote this code, I processed the data in a supercomputer, and because it had a ridiculous large RAM, I loaded everything I could into memory. I can look at it and try to get rid of non-essential stuff to decrease the amount of memory needed to run the scripts.

However, if you are not interested in *exactly* replicating the results, I suggest you also take a look at [Hypnospy](https://github.com/ippozuelo/HypnosPy/), a new package under development to process wearable data. I will be glad to provide a full script based on HypnosPy to process the MESA data and largely duplicate the results in the paper. 

Let me know your thoughts and I am also available by email if you prefer.

Best,

Joao

**Comment by aaronjfisher** [comment]
Thanks for your fast reply!

Exact results aren't necessary, and it's probably better for me to be working with your more recent and active implementations of these methods, rather than a repo that's meant to be static so that it can always reproduce a paper. Hypnospy sounds perfect.  I'm trying to get oriented to the hypnospy structure now, and might ask/email you questions about it as I go (if you have time!).

**Comment by joaopalotti** [comment]
Sure! I will be happy to help with anything you need. 
Currently, the package documentation is a little bit outdated, but I am happy to answer any further questions.
Feel free to share your suggestions and requests if you have any.

Best,
Joao
